### PR TITLE
build system cleanup

### PR DESCRIPTION
**Pull request by garlick**
This PR is just a batch of misc cleanup, primariily aimed at the build system.  Still more cleanup coming but this seemd like a reasonable place to stop for a first pass.

@ofaaland let me know what you think and press the button if you have no objections.  Thanks!

### CODE REVIEW

**Review by ofaaland — APPROVED** [review]

**Comment by garlick** [comment]
@ofaaland - actually if you don't mind pushing merge button, I'll submit the next batch as a separate PR.  Thanks!

**Comment by ofaaland** [comment]
@garlick  looks like I don't have write access.  I must only have it on the LLNL org.  Can you add me?

**Comment by garlick** [comment]
Sorry about that!  Try now?

**Comment by garlick** [comment]
Thanks very much!

**Pull request merged**
