### PR TITLE
build: make rquota pass make distcheck, enable travis

### PR DESCRIPTION
**Pull request by garlick**
This PR makes some necessary changes to get rquota building in travis, and fixes some issues with `make distcheck`, which tests the automake feature of building outside of the source tree, e.g.
```
$ mkdir mybuild
$ cd mybuild
$ ../configure
$ make
...
```

The sunrpc `rpcgen` utility doesn't play very well wtih automake, and a couple of non-obvious tricks, well documented in commit messages, were needed to make it builddir/srcdir aware.  It seemed more orderly to isolate this code and its generated .c and .h files in their own subdirectory, so I split up the src dir into several chunks, with that part built as a little library, `librpc`. 

The other problem area was the test suite.  I got rid of the `runtests` front and and just used the built-in one supplied by automake.  The little numbered scripts all needed to be edited again to make them builddir/srcdir aware.  I ended up reverting the mktemp change just merged in #12 because it wasn't needed after all, and I wanted to track the way [powerman](https://github.com/chaos/powerman)''s test suite had been updated, to avoid having too many differences between project test suites.  Eventaully we'll probably want to go TAP (#5) but not yet.

### CODE REVIEW

**Comment by garlick** [comment]
Er, I see a little problem in the librpc Makefile.am, let me fix that.

**Comment by garlick** [comment]
Fixed, and also added code to find `rpcgen` at configure time.

I also attempted to add some test infrastructure for NFS quotas.  `make check` now builds a test client and server in `librpc`.  The client might be useful for checking exactly what values a server is returning when the post processed `quota` or `repquota` output isn't looking right.  Maybe the server can be adapted to run in a test at some point - right now I think it only works if the real quota service is not running so would be inappropriate for running under travis, for example.

**Comment by garlick** [comment]
I backed out that test program since it doesn't really have anything to do with the topic of this PR.  (I'll put it in the next PR that will tweak the RPC timeouts, since I used it for testing that).

The incremental development has been squashed, and I also turned on `-Werror` and fixed one warning on gcc-7.

I think this is ready for a review/merge.

**Comment by garlick** [comment]
As discussed offline, I tacked on a couple commits that allow rquota to be built in travis `--with-lustre`.

**Review by ofaaland — APPROVED** [review]
LGTM

**Comment by garlick** [comment]
Thanks!

**Pull request merged**
